### ISSUE TITLE
Reintroduce scientific topic on courses/events page 

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#105]
It should be similar to how we did for venues so the data is not duplicate based on lowercase or uppercase thing.

**Comment by harshita3199** [comment]
It should be multi select field and no other users are able to add anything, just us adding the content from admin panel. Ex: DDLS, Precision Medicine.
Content Provider : Scilifelab

**Comment by harshita3199** [comment]
Updating the ticket for scientific topic working as per TeSS:
it uses an "autocompleter" widget:
https://github.com/ElixirTeSS/TeSS/blob/ea2081b36f475a69a93fcf80a5f7702995cd018a/app/views/events/_form.html.erb#L105-L108
defined here:
https://github.com/ElixirTeSS/TeSS/blob/0bbda8474a2d5b241911b4c9cc3542173ba944fa/app/helpers/application_helper.rb#L377-L390
and in the scientific topics case, it queries a simple JSON endpoint to get the autocomplete suggestions: https://github.com/ElixirTeSS/TeSS/blob/eda98291be3b49d5eb4ac8dc3c308aa57729a6de/app/controllers/edam_controller.rb

**Comment by harshita3199** [comment]
Updating the ticket for scientific topic working as per TeSS:
it uses an "autocompleter" widget:
https://github.com/ElixirTeSS/TeSS/blob/ea2081b36f475a69a93fcf80a5f7702995cd018a/app/views/events/_form.html.erb#L105-L108
defined here:
https://github.com/ElixirTeSS/TeSS/blob/0bbda8474a2d5b241911b4c9cc3542173ba944fa/app/helpers/application_helper.rb#L377-L390
and in the scientific topics case, it queries a simple JSON endpoint to get the autocomplete suggestions: https://github.com/ElixirTeSS/TeSS/blob/eda98291be3b49d5eb4ac8dc3c308aa57729a6de/app/controllers/edam_controller.rb

**Comment by adeel-ahmad-awan** [comment]
we need to ask @ninanorgren that 

- can we as an admin add new topics because right now the topics are being imported from http://edamontology.org


Uptill now we have enabled scientific topic which is a multi select, the following are the screen shots for the currect progress

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC9qQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97b2360d3084578a65b57011c7b38047f9171199/image.png" alt="image.png" />
<img width="351" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b7f851ee8e2f0187d84028095521c0b8c1390e3/image.png" alt="image.png" />

**Comment by harshita3199** [comment]
Done and merged in develop branch
