### ISSUE TITLE
automate event moderation email to user

### ISSUE THREAD

**Issue by kristen-schroeder** [SciLifeLab-TrainingHub-Platform/TeSS#181]
if i am a user 
and I click "add event" on the portal
and the required fields are correct
i will receive a confirmation email with information on what is going to happen with my event next

**Comment by harshita3199** [comment]
**Breakdown of tasks for event automation**

- [x] - Send the event request to admin so that they can approve or reject through admin console. (dropdown field, reject, approve and changes requested)
- [x] - Email should be sent to the user for notifying them + email template
- [x] - Email should be sent to the traininghub@scilifelab.se + email template
- [x] - We want the user to edit the event as much as they want & it will be moderated.
- [x] - Save as draft feature can be provided in future for the event(for future)--created the ticket in icebox
- [x] - Make fields mandatory for the events before saving it as per Kristen's MARKED UP IMAGE
- [x] - change the backend that user could see the event that they have created but not published publicly and general user should only see published events----we need to change the colour coding of the unmoderated event how it should look, Kristen would be helping us here
- [x] - Email template for manually rejecting the event, and there would be a send mail button for automatic sending the mail for approved events--not moving forward with send mail button thingy
- [x] - Manually change the role to trusted user from the default user through admin console (updated in the workflow on confluence)

**Comment by harshita3199** [comment]
**We would like to show the below text on the banner in the portal once the event is submitted by the user**
_Your training was successfully received and is pending approval_

**Comment by kristen-schroeder** [comment]
suggestions for casual-izing the email body text:

Hi (user),

Congratulations, your training event titled (coursename) has been successfully submitted on the SciLifeLab Training Portal.

Event details:
**Event title
URL
Start Date
End Date**

Your training event is now under review by our team!

The next steps are:
- If approved, your training event will be published and visible on the SciLifeLab Training Portal
- If the event requires any changes, you will get an email from one of our admins.
- If the event is declined, we will send you an email with the reason for our decision and it will be removed from the Portal.

You can view and manage your event using the link below:

VIEW EVENT BUTTON

Thank you for being a part of our community!

**Comment by harshita3199** [comment]
@kristen-schroeder This email is just for submission. Will you be providing the template for event publishing as well in regards to users?

**Comment by kristen-schroeder** [comment]
självklart! for @adeel-ahmad-awan :

Hi (user),

Your training event titled (coursename) is now live on the Training Portal!

(VIEW EVENT BUTTON)

If you've found a typo or need to update your venue you can do so via the 'Edit' button on your event page. Training events are pulled from the Training Portal into the SciLifeLab Newsletter every other week and shared with communities based on keywords, so we hope you will have many registrations!

Thank you for being a part of our community!

**Comment by harshita3199** [comment]
Thank you @kristen-schroeder

**Comment by adeel-ahmad-awan** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--161edf21976c608107369f71bf0425eaba56d982/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3381dc0a096bb4c90bd0a0b6684609090ea342a8/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bc9159d66c0a4ac43db0cdc79c71b5c369535ce/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ddebe45cc25d20a38fb4bdabd9a91fdb9d4f187/image.png" alt="image.png" />

**Comment by kristen-schroeder** [comment]
majestic!
