### ISSUE TITLE
Resolve Node Duplication in `db:seed` Command

### ISSUE THREAD

**Issue by adeel-ahmad-awan** [SciLifeLab-TrainingHub-Platform/TeSS#215]
There is an issue where running the `bin/rails node:create_entries` command to create entries for custom nodes (e.g., SciLifeLab and External) is followed by the `db:seed` command for trusted user configuration. 

The `db:seed` process inserts nodes from the `elixir_nodes.json` file, causing duplicate entries (e.g., Sweden) in the Node section.

**Comment by adeel-ahmad-awan** [comment]
https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/216

**Comment by harshita3199** [comment]
In localhost, I already had Scilifelab, External and Sweden nodes. SO when I tried running db:seed command it failed returning duplication error so I had to manually delete all the three nodes and then it ran successfully.  
But then I think we cannot rerun this command again or utilise this command later because once we have the nodes inserted and trusted user inserted then I think it will fail due to the below error. But now I am thinking do we need this command in the longer run or should we go by utilising this command. I think we are good as we included this in db:seed in order to initialise the database if anyone uses our portal


Error for reference: 
Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_nodes_on_slug" (PG::UniqueViolation)
DETAIL:  Key (slug)=(scilife_lab) already exists.
/usr/local/bundle/gems/activerecord-7.0.8.4/lib/act

**Comment by adeel-ahmad-awan** [comment]
Based on our discussion, the duplicate entry errors occur because the nodes already exist due to the execution of the `bin/rails node:create_entries` command.

Once these existing entries are removed, the command can be run multiple times without errors, consistently resulting in the creation of only two nodes.

Furthermore, since the `bin/rails node:create_entries` command has not been executed on any server, we can be reasonably confident that there will be no issues when seeding the database on the server.
