### ISSUE TITLE
Resolve all the test cases 

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#97]

**Comment by harshita3199** [comment]
We can keep html test cases if they are working otherwise remove them.

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/168

right now only 2 cases are failing and 1 error

**DeviseMailerTest#test_mailer_headers_are_applied_to_emails_from_devise**
Assertion: 1 emails expected, but 0 were sent

- the reason is that we have not added email service keys to local


**RegistrationsControllerTest#test_should_register_user**
Assertion: "User.count" didn't change by 1

- the reason is that we have disabled signup route
 
**RegistrationsControllerTest#test_should_not_register_user_when_no_consent_given**
 undefined method `errors' for nil:NilClass

- the reason is that we have disabled signup route

p.s. please see attached the test result


[zoutput.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bc52ef8736546cae407abf4f04f1ba5924494bd/zoutput.txt)
